syntax:
  must_include:
    - "@(cross("
    - "transition("
dut_compile:
  backend: "evas"
tb_compile:
  backend: "evas"
sim_correct:
  checks:
    - "dac_output_monotonic"
    - "dac_output_range_sufficient"
