syntax:
  must_include:
    - "@(cross("
    - "transition("
dut_compile:
  backend: "evas"
tb_compile:
  backend: "evas"
sim_correct:
  checks:
    - "output_inverts_input"
    - "invert_match_frac > 0.9"