syntax:
  must_include:
    - "@(cross("
    - "transition("
dut_compile:
  backend: "evas"
tb_compile:
  backend: "evas"
sim_correct:
  checks:
    - "sar_adc_code_range_sufficient"
    - "sar_adc_unique_code_count"
    - "dac_output_in_range"
