syntax:
  must_include:
    - "@(cross("
    - "@(timer("
    - "transition("
dut_compile:
  backend: "evas"
tb_compile:
  backend: "evas"
sim_correct:
  checks:
    - "adpll_ratio_hop_pre_ratio"
    - "adpll_ratio_hop_post_ratio"
    - "adpll_ratio_hop_lock_reacquired"
