syntax:
  must_include:
    - "@(cross("
    - "transition("
dut_compile:
  backend: "evas"
tb_compile:
  backend: "evas"
sim_correct:
  checks:
    - "pfd_reset_race_short_up_pulses"
    - "pfd_reset_race_short_dn_pulses"
    - "pfd_reset_race_no_long_overlap"
